apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: calico-node 
  namespace: calico-system
spec:
  template:
    metadata:
      labels:
        name: calico-node 
    spec:
      nodeSelector:
      hostNetwork: true
      containers:
        - env:
            - name: ETCD_AUTHORITY 
              value: 172.18.18.101:2379 
          image: calico/ctl:latest 
          name: calico-ctl 
          args:
            - node
            - --detach=false
          volumeMounts:
            - mountPath: /var/run
              name: var-run
      volumes:
        - name: var-run
          hostPath:
            path: /var/run
