apiVersion: v1
kind: Service
metadata:
  name: backend 
spec:
  ports:
  - port: 6379
    targetPort: 6379 
  selector:
    tier: backend 
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: backend 
spec:
  replicas: 2
  template:
    metadata:
      labels:
        tier: backend 
    spec:
      containers:
      - name: backend 
        image: caseydavenport/backend
        imagePullPolicy: Always
        ports:
        - containerPort: 6379 
