apiVersion: v1
kind: Service
metadata:
  name: frontend 
spec:
  type: NodePort
  ports:
  - port: 80 
    targetPort: 80 
    nodePort: 30001
  selector:
    tier: frontend 
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend 
spec:
  replicas: 3
  template:
    metadata:
      labels:
        tier: frontend 
    spec:
      containers:
      - name: frontend 
        image: caseydavenport/frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80 
