apiVersion: v1
kind: ReplicationController
metadata:
  name: backend 
spec:
  replicas: 2
  template:
    metadata:
      labels:
        tier: backend 
    spec:
      containers:
      - name: nginx 
        image: caseydavenport/probe
        imagePullPolicy: Always
        ports:
        - containerPort: 9000 
