apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend 
spec:
  replicas: 3
  template:
    metadata:
      labels:
        tier: frontend 
    spec:
      containers:
      - name: nginx 
        image: caseydavenport/probe 
        imagePullPolicy: Always
        ports:
        - containerPort: 80 
