apiVersion: v1
kind: Pod 
metadata:
  name: calico-policy-agent
  namespace: calico-system
  labels:
    version: latest
    projectcalico.org/app: "policy-agent"
spec:
  hostNetwork: true
  containers:
    # The Calico policy agent.
    - name: policyagent    
      image: caseydavenport/k8s-policy-agent:leadership
      imagePullPolicy: IfNotPresent
      env:
        - name: ETCD_AUTHORITY
          value: "127.0.0.1:2379"
        - name: K8S_API
          value: "http://127.0.0.1:8080"
        - name: LOG_LEVEL
          value: "info"

    # Leader election container used by the agent.
    - name: leaderelect
      image: gcr.io/google_containers/leader-elector:0.4
      imagePullPolicy: IfNotPresent
      args:
        - "--election=calico-policy-election"
        - "--http=127.0.0.1:4040"
      ports:
        - containerPort: 4040
          protocol: TCP
