apiVersion: v1
kind: ReplicationController
metadata:
  name: getter 
spec:
  replicas: 0 
  selector:
    role: getter 
  template:
    metadata:
      labels:
        role: getter 
    spec:
      containers:
      - name: getter 
        image: caseydavenport/scale-tester
        env:
        - name: TIMEOUT
          value: ".1"
        - name: SLEEPTIME 
          value: "0"
