apiVersion: v1
kind: Service
metadata: 
  name: test
spec:
  selector:
    k8s-app: nginx-server
  ports:
  - port: 80 
    targetPort: 80 
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-server 
spec:
  replicas: 1
  selector:
    k8s-app: nginx-server 
  template:
    metadata:
      labels:
        k8s-app: nginx-server 
    spec:
      containers:
      - name: nginx 
        image: caseydavenport/nginx 
