apiVersion: v1
kind: Namespace
metadata:
  name: calico-system
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: calico-policy-agent
  namespace: calico-system 
  labels:
    version: latest
    projectcalico.org/app: "policy-agent"
spec:
  replicas: 1
  selector:
    version: latest
    projectcalico.org/app: "policy-agent"
  template:
    metadata:
      labels:
        version: latest
        projectcalico.org/app: "policy-agent"
    spec:
      containers:
        - name: policyagent    
          image: caseydavenport/k8s-policy-agent:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          env:
          - name: ETCD_AUTHORITY
            value: "172.18.18.101:2379"
          - name: K8S_API
            value: "https://kubernetes.default:443"
          - name: LOG_LEVEL
            value: "info"
